name: RulerGem
version: 1.0.1
main: me.hushu.RulerGem
author: angushushu
description: "一个管理 RulerGem（权力宝石）的示例插件"

# 如果你的插件需要在更高版本的 Spigot/Paper 运行，可以指定 api-version
api-version: "1.16"
folia-supported: true
depend: [Vault]
commands:
  rulergem:
    usage: /<command> <place|revoke|reload|rulers|gems|scatter|redeem|redeemall|help>
    description: RulerGem plugin command
    aliases: [rg]
    permission: 

permissions:
  rulergem.admin:
    description: Allows access to all RulerGem commands
    default: op
  rulergem.redeem:
    description: Allows using /rulergem redeem
    default: true
  rulergem.redeemall:
    description: Allows using /rulergem redeemall
    default: true
  rulergem.rulers:
    description: Allows using /rulergem rulers
    default: true
  rulergem.help:
    description: Allows using /rulergem help
    default: true
