name: RuleGems
version: 1.0.2
main: org.cubexmc.RuleGems
author: angushushu
description: "一个管理 RuleGems（统治宝石）的插件"

# 如果你的插件需要在更高版本的 Spigot/Paper 运行，可以指定 api-version
api-version: "1.16"
folia-supported: true
depend: [Vault]
commands:
  rulegems:
    usage: /<command> <place|revoke|reload|rulers|gems|scatter|redeem|redeemall|help>
    description: RuleGems plugin command
    aliases: [rg]
    permission: 

permissions:
  rulegems.admin:
    description: Allows access to all RuleGems commands
    default: op
  rulegems.redeem:
    description: Allows using /rulegems redeem
    default: true
  rulegems.redeemall:
    description: Allows using /rulegems redeemall
    default: true
  rulegems.rulers:
    description: Allows using /rulegems rulers
    default: true
  rulegems.help:
    description: Allows using /rulegems help
    default: true
